// Pattachote keyboard layout mapping
// Maps English QWERTY keys → Thai characters (Pattachote layout)

export const EN_TO_TH_PATTACHOTE: Record<string, string> = {
  // Number row
  '`': '_',
  '1': '=',
  '2': '๒',
  '3': '๓',
  '4': '๔',
  '5': '๕',
  '6': 'ู',
  '7': '็',
  '8': '๘',
  '9': '๙',
  '0': '๐',
  '-': '๑',
  '=': '๖',
  // QWERTY row
  'q': '็',
  'w': 'ต',
  'e': 'ย',
  'r': 'อ',
  't': 'ร',
  'y': '่',
  'u': 'ด',
  'i': 'ม',
  'o': 'ว',
  'p': 'แ',
  '[': 'ใ',
  ']': 'ฌ',
  '\\': 'ฃ',
  // Home row
  'a': '้',
  's': 'ท',
  'd': 'ง',
  'f': 'ก',
  'g': 'ั',
  'h': 'ี',
  'j': 'า',
  'k': 'น',
  'l': 'เ',
  ';': 'ไ',
  "'": 'ข',
  // Bottom row
  'z': 'บ',
  'x': 'ป',
  'c': 'ล',
  'v': 'ห',
  'b': 'ิ',
  'n': 'ส',
  'm': 'ะ',
  ',': 'จ',
  '.': 'พ',
  '/': 'ฎ',
};

export const EN_TO_TH_PATTACHOTE_SHIFT: Record<string, string> = {
  '~': '%',
  '!': '+',
  '@': '๒',
  '#': '/',
  '$': ',',
  '%': '-',
  '^': 'ุ',
  '&': 'ึ',
  '*': 'ค',
  '(': 'ต',
  ')': 'จ',
  '_': 'ข',
  '+': 'ช',
  'Q': '๊',
  'W': 'ฤ',
  'E': 'ๆ',
  'R': 'ฯ',
  'T': 'ฑ',
  'Y': 'ธ',
  'U': 'ำ',
  'I': 'ณ',
  'O': 'ฒ',
  'P': 'ฬ',
  '{': 'ฦ',
  '}': 'ฅ',
  '|': '?',
  'A': '๋',
  'S': 'ษ',
  'D': 'ซ',
  'F': 'โ',
  'G': 'ฌ',
  'H': 'ํ',
  'J': 'ื',
  'K': '์',
  'L': 'ศ',
  ':': 'ภ',
  '"': 'ฎ',
  'Z': 'ฐ',
  'X': '(',
  'C': ')',
  'V': 'ฮ',
  'B': 'ฺ',
  'N': 'ฉ',
  'M': 'ฆ',
  '<': 'ฏ',
  '>': 'ญ',
  '?': 'ฦ',
};

export const FULL_EN_TO_TH_PATTACHOTE: Record<string, string> = {
  ...EN_TO_TH_PATTACHOTE,
  ...EN_TO_TH_PATTACHOTE_SHIFT,
};

export const FULL_TH_TO_EN_PATTACHOTE: Record<string, string> = {};
for (const [en, th] of Object.entries(FULL_EN_TO_TH_PATTACHOTE)) {
  FULL_TH_TO_EN_PATTACHOTE[th] = en;
}
